site_name: Town Of Host
site_url: https://hyz-sui.github.io/town-of-host-docs
repo_url: https://github.com/tukasa0001/TownOfHost
copyright: "&copy; 2025 Hyz-sui, town-of-host-docs contributors"
repo_name: tukasa0001/TownOfHost
theme:
  name: material
  favicon: assets/icon.png
  custom_dir: overrides
  icon:
    logo: material/home
    repo: material/github
  palette:
    # 自動
    - media: "(prefers-color-scheme)"
      primary: light blue
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: green
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: green
      toggle:
        icon: material/lightbulb-auto
        name: Switch to system preference
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.indexes
    - search.suggest
    - header.autohide
  font:
    text: Roboto
    code: Fira Code
extra_css:
  - extra.css
plugins:
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
          nav_translations:
            10 roles: Roles
            Addons: Add-ons
            Crewmates: Crewmate Roles
            Impostors: Impostor Roles
            Neutrals: Neutral Roles
            Others: Other Roles
        - locale: ja
          name: 日本語
          build: true
          admonition_translations:
            tip: ヒント
            warning: 注意
            note: メモ
            info: 情報
            abstract: 要約
            success: 成功
            failure: 失敗
            question: 疑問
            danger: 危険
            bug: 不具合
            example: 例
            quote: 引用
          nav_translations:
            10 roles: 追加役職
            Addons: 属性
            Crewmates: クルー役職
            Impostors: インポスター役職
            Neutrals: ニュートラル役職
            Others: その他の追加役職
  - search
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
hooks:
  - hooks/share.py
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - toc:
      permalink: "#"
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.keys
  - footnotes
  - md_in_html
extra:
  generator: true
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/W5ug6hXB9V
    - icon: fontawesome/brands/github
      link: https://github.com/tukasa0001/TownOfHost
